name: Python JHeaps

on:
  push:
    branches:
      - actions

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: dmichail/manylinux:1634888a5feacaf6c3b8e4d181d00fee57b390b4
    strategy:
      fail-fast: false
    steps:
    - name: OS?
      run: | 
        uname -a
    - name: ls GITHUB_WORKSPACE
      run: |
        ls $GITHUB_WORKSPACE
    - name: Clone repository
      run: |
        git clone --recursive --branch actions https://github.com/d-michail/python-jheaps.git $GITHUB_WORKSPACE/../python-jheaps
    - name: ls GITHUB_WORKSPACE
      run: |
        ls $GITHUB_WORKSPACE
    - name: cat GITHUB_WORKSPACE/.github/scripts/build-manylinux2010_x86_64.sh
      run: |
        cat GITHUB_WORKSPACE/.github/scripts/build-manylinux2010_x86_64.sh
    - name: Build
      run:  $GITHUB_WORKSPACE/.github/scripts/build-manylinux2010_x86_64.sh
      shell: bash

  build-other:
    if: false
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows 2019 - MSVC",
            os: windows-2019,
            python-version: "3.9",
            gu: "gu.cmd",
          }        
        - {
            name: "Windows 2019 - MSVC",
            os: windows-2019,
            python-version: "3.8",
            gu: "gu.cmd",
          }
        - {
            name: "Windows 2019 - MSVC",
            os: windows-2019,
            python-version: "3.7",
            gu: "gu.cmd",
          }
        - {
            name: "Windows 2019 - MSVC",
            os: windows-2019,
            python-version: "3.6",
            gu: "gu.cmd",
          }
        - {
            name: "MacOS 10.15",
            os: macos-10.15,
            python-version: "3.9",
            gu: "gu"
          }
        - {
            name: "MacOS 10.15",
            os: macos-10.15,
            python-version: "3.8",
            gu: "gu"
          }
        - {
            name: "MacOS 10.15",
            os: macos-10.15,
            python-version: "3.7",
            gu: "gu"
          }
        - {
            name: "MacOS 10.15",
            os: macos-10.15,
            python-version: "3.6",
            gu: "gu"
          }
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}
        architecture: x64
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
    - name: Setup GraalVM
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      id: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.0.0.2'
        java: 'java11'
        arch: 'amd64'
    - name: Install native-image component
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      run: |
        ${{ matrix.config.gu }} install native-image
    - name: Install swig (MacOS)
      if: runner.os == 'MacOS'
      run: |
        brew install swig
    - name: Install swig (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install swig --version=4.0.1
    - name: Build Library
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      run: |
        pip install wheel
        python setup.py bdist_wheel
    - name: Install and run tests
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      run: |
        pip install -r requirements/test.txt
        pip install jheaps --no-index -f dist/
        pytest


