name: Python JHeaps

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "MacOS 10.15",
            os: macos-10.15,
            python-version: "3.8"
          }
        - {
            name: "MacOS 10.15",
            os: macos-10.15,
            python-version: "3.7"
          }
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}
        architecture: x64
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
