name: Python JHeaps

on:
  push:
    branches:
      - actions

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: dmichail/manylinux:ffb75cb3ba93612b26c4169988a49c50530e8ac4
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: OS?
      run: | 
        uname -a
    - name: Build
      run: ./.github/scripts/build-manylinux2010_x86_64.sh
      shell: bash

  build-other:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows 2019 - MSVC",
            os: windows-2019,
            python-version: "3.9",
            gu: "gu.cmd",
          }        
          #- {
          #    name: "Windows 2019 - MSVC",
          #    os: windows-2019,
          #    python-version: "3.8",
          #    gu: "gu.cmd",
          #  }
          #- {
          #    name: "Windows 2019 - MSVC",
          #    os: windows-2019,
          #    python-version: "3.7",
          #    gu: "gu.cmd",
          #  }
          #- {
          #    name: "Windows 2019 - MSVC",
          #    os: windows-2019,
          #    python-version: "3.6",
          #    gu: "gu.cmd",
          #  }
          #- {
          #  name: "MacOS 10.15",
          #  os: macos-10.15,
          #  python-version: "3.9",
          #  gu: "gu"
          #}
          #        - {
          #            name: "MacOS 10.15",
          #            os: macos-10.15,
          #            python-version: "3.8",
          #            gu: "gu"
          #          }
          #        - {
          #            name: "MacOS 10.15",
          #            os: macos-10.15,
          #            python-version: "3.7",
          #            gu: "gu"
          #          }
          #        - {
          #            name: "MacOS 10.15",
          #            os: macos-10.15,
          #            python-version: "3.6",
          #            gu: "gu"
          #          }
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}
        architecture: x64
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
    - name: Setup GraalVM
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      id: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.0.0.2'
        java: 'java11'
        arch: 'amd64'
    - name: Install native-image component
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      run: |
        ${{ matrix.config.gu }} install native-image
    - name: Install swig (MacOS)
      if: runner.os == 'MacOS'
      run: |
        brew install swig
    - name: Install swig (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install swig --version=4.0.1
    - name: Build Library
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      run: |
        pip install wheel
        python setup.py bdist_wheel
    - name: Install and run tests
      if: runner.os == 'MacOS' || runner.os == 'Windows'
      run: |
        pip install -r requirements/test.txt
        pip install jheaps --no-index -f dist/
        pytest


